### PR TITLE
Fix for issue #212

### LINKED ISSUE #212: There is an issue on mobile frontpage when too few events
There is an bug on mobile when there is too few events to showcase. We should sort the events by type on mobile.

Here is a screenshot showcasing the bug:
bilde

### PR DESCRIPTION
**Pull request by mariush2**
# This pull request aims to fix #212.
We now have columns for "Bedpres", "Kurs" and "Sosialt/Annet". This also means that the view on mobile is the way described in #212, meaning we now show all the events of each column after one another (List-items after Card-items).

## Here is a screenshot from before:
<p align="center">
before
</p>

## Here is a screenshot after the fix:
<p align="center">
after
</p>

### CODE REVIEW

File: src/events/components/ImageView/index.tsx [hunk 1]
```diff
@@ -82,27 +82,37 @@ export const ImageView = ({  }: IProps) => {
...
+        <div className={style.eventColumn}>
+          {displayEvents.eventsLeft[0] ? (
+            <>
+              <LargeEvent {...displayEvents.eventsLeft[0]} />
+              <SmallEventColumn events={displayEvents.eventsLeft.slice(1, 4)} />
+            </>
+          ) : (
+            <LargeEventPlaceholder event_type={2} />
+          )}
+        </div>
```
Comment (oleast) [inline src/events/components/ImageView/index.tsx]: This almost exact block code is repeated 3 times, consider making it a Component?
