### PR TITLE
Fix frontpage image view spacing and default image

### LINKED ISSUE #245: Event card not appearing in ImageView
**Describe the bug**

The event card for "Eksamensforelesning - Databse" does not appear on the front page

**To Reproduce**
1. Go to beta.online.ntnu.no
2. Observe missing event card

**Expected behavior**

The event card appears

**Screenshots**
Screenshot 2019-04-30 at 12 17 56

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: newest

**Additional context**
The event that doesn't appear is https://beta.online.ntnu.no/events/702
width > 1024px

### PR DESCRIPTION
**Pull request by oleast**
Fix #245

## Old

ImageViewOld

## New

ImageViewFix

# Old

ImageViewSmallOld

# New

ImageViewSmallFix

### CODE REVIEW

File: src/events/components/DetailView/PictureCard.tsx [hunk 1]
```diff
@@ -17,8 +17,9 @@ const PictureCard = ({ image, event_start, event_end, location, company_event, e
 
   return (
     <div className={style.pictureCard}>
-      <EventImage companyEvents={company_event} image={image} size="md" />
-
+      <div>
+        <EventImage companyEvents={company_event} image={image} size="md" color={color} />
+      </div>
```
Comment (henrikhorluck) [inline src/events/components/DetailView/PictureCard.tsx]: Is the div necessary here?
