### PR TITLE
Avoid partial event attendees

### LINKED ISSUE #507: Event statistics shows partial event attendees which is not an option
**Describe the bug**  

Event statistics "commit"-view shows floats instead of integers.
This makes little sense as we do not have the option to attend half an event.

**To Reproduce**
1. Go to https://online.ntnu.no/profile/statistics/events
2. Scroll down to 'Arrangementsdatoer'

**Expected behavior**

Events being whole numbers

**Screenshots**

### PR DESCRIPTION
**Pull request by CarlOfHoly**
Sets the item count for each nivo-calender by finding the max possible value.

closes #507

### CODE REVIEW

File: src/common/components/Charts/CalendarChart.tsx [hunk 1]
```diff
@@ -23,12 +23,12 @@ const MARGINS = {
...
 };
 
-const LEGENDS: CalendarLegend[] = [
+const LEGENDS = (itemCount: number): CalendarLegend[] => [
   {
     anchor: 'bottom-right',
     direction: 'row',
     translateY: 36,
-    itemCount: 4,
+    itemCount,
```
Comment (FluidSense) [inline src/common/components/Charts/CalendarChart.tsx:31]: Wouldn't this have to be `itemCount: itemCount`?

Comment (FluidSense) [reply src/common/components/Charts/CalendarChart.tsx:31]: ...apparently not 😂

**Review by FluidSense — APPROVED** [review]
Nice! I've noticed that the grid is gone (if we ever had one..!), but that could be another PR!
